FROM ghcr.io/yinjiayi/k3s-alpine:3.20-riscv64.1

ENV TZ=UTC
RUN sed -i \
        's!https://dl-cdn.alpinelinux.org/alpine/!https://mirrors.aliyun.com/alpine/!g' \
        /etc/apk/repositories
RUN apk --no-cache add \
        bash \
        build-base \
        ca-certificates \
        curl \
        git \
        mariadb-client \
        mariadb-dev \
        openssh-client \
        openssl \
        py3-cryptography \
        py3-pip \
        py3-yaml \
        python3 \
        python3-dev \
        rsync \
        sshpass \
        sudo && \
    python3 -m pip install \
        --index-url https://repo.huaweicloud.com/repository/pypi/simple \
        --break-system-packages \
        --no-cache-dir \
        mysqlclient==2.2.8 pywinrm==0.5.0 ansible==8.7.0 && \
    apk del build-base mariadb-dev python3-dev

ENV K3S_AIRGAP_DIR=/ocboot/airgap_assets
ENV PATH=$PATH:/ocboot
WORKDIR /ocboot
